### ISSUE TITLE
Issue on serialise/deserialise a complex map?

### ISSUE THREAD

**Issue by im-sanyam** [Tessil/hat-trie#22]
Hi,

I am trying to use the hat_trie in my project.
But I am facing an issue on serializing the following:

`tsl::htrie_map<char,set<pair<ll,string>>> data[N];` 

Here, it's a multidimensional map trying to store char as key and set of pair of integers and strings as a value to it.
Can you help me out?

**Comment by Tessil** [comment]
Hi,

Could you give some details on your problem? Do you use an additional serialization library?

**Comment by im-sanyam** [comment]
I was trying to use the boost library but the data structure defined was not friendly enough to get serialized. I also took the reference of Issue #21 but could not find any solution.

**Comment by Tessil** [comment]
Could you provide a minimal code example? What is your issue exactly, compilation error or run-time error?
