### ISSUE TITLE
Retrieving sorted keys

### ISSUE THREAD

**Issue by mr-eyes** [Tessil/hat-trie#24]
Hi,

I'm using the `tsl::htrie_map` for inserting DNA fixed-size strings as keys (4-bases ACGT).
Is there any option to iterate over sorted keys? I didn't find anything related to that in the documentations.

Thanks.

**Comment by Tessil** [comment]
Unfortunately it's isn't currently possible. It could be possible to sort the keys in the hash map part of the HAT-Trie while iterating but I think other trie structures may be better suited if the keys need to be sorted.
