### ISSUE TITLE
Wildcard search support ?

### ISSUE THREAD

**Issue by Rockybilly** [Tessil/hat-trie#28]
Does this implementation has wildcard search support using the advantages of a trie (So that performance may increase, not needing to iterate over whole string) ?

By wildcard I mean `*` and `?` included pattern search.

**Comment by Tessil** [comment]
Hi,

The implementation only supports prefix searches, so something like `foo*` is supported but not `foo*bar*` nor `*bar` as they would not be efficient with this structure.
