### ISSUE TITLE
trie using integer keys?

### ISSUE THREAD

**Issue by greg7mdp** [Tessil/hat-trie#29]
Hi there, just a question, do you have a trie storing integer keys?
Thanks, - greg

**Comment by degski** [comment]
If the key's somehow have some coherence (could be ip's (sub-nets)) then you could break down the int in 4 chars and use that as a key (i.e. convert the int notionally to string, in C++17 you can just (after resizing) the int with `std::memcpy` into a `std::string` (legalized type-punning)). The memcpy will be optimized away and the binary code will do what you would like it to do.

**Comment by greg7mdp** [comment]
Thank you very much, @degski ! I just realized this hat-trie is not ordered which I need.

**Comment by Tessil** [comment]
Hi,

The current HAT-Trie, in addition of not being ordered, may also not be the most efficient for storing integers, even when split by byte, it's more specialized for strings. I know there is the [Y-fast trie](https://en.wikipedia.org/wiki/Y-fast_trie) but I never tested any implementation. There is also [nedtries](https://github.com/ned14/nedtries) for integers but I never tested it either.

Thibaut

**Comment by degski** [comment]
> 
> 
> Thank you very much, @degski ! I just realized this hat-trie is not ordered which I need.

I suspected that, that's what I meant with 'coherence'. A trie (in it's simplest form, not this one) stores words in trees with the letters (char's) as ever deepening keys of the tree's nodes, so all the words with a 2nd letter 'b' f.e. are in a sub-tree with root key 'b', and so on. 

Just use a hash tree (if the keys are 'random' enough, particularly the low bits, you might get away by just using the identity function for hashing into the hash map, which would make it very cheap.

**Comment by greg7mdp** [comment]
thanks @degski, would a hash tree preserve ordering? Do you have an example of this? 
Thanks - greg

**Comment by degski** [comment]
> 
> 
> Thank you very much, @degski ! I just realized this hat-trie is not ordered which I need.

It's ordered, but lexicographically, that's why it applies to strings.

**Comment by degski** [comment]
> 
> 
> thanks @degski, would a hash tree preserve ordering? Do you have an example of this?

No, that's what the hash tree will do as well, as it grows it will 'consume' more bits of your key. It is the low bits that matter the most.

> Even when using the identity function for hash, the modulo would mess up the ordering right?

What order do you want to preserve, you did not define that?

**Comment by greg7mdp** [comment]
I want to use integer keys (for example uint32_t). I need to be able to traverse the tree in sorted fashion (< for uint32_t), and to query the min and max integer keys at any time.

**Comment by degski** [comment]
> 
> 
> I want to use integer keys (for example uint32_t). I need to be able to traverse the tree in sorted fashion (< for uint32_t), and to query the min and max integer keys at any time.

`std::map`.

**Comment by greg7mdp** [comment]
yes, I know. Actually cpp-btree or [abseil btree](https://abseil.io/blog/20190812-btree) are better. But I was looking to faster lookups.

**Comment by greg7mdp** [comment]
> or better, create an intrusive map with std::set, i.e. the 'key' consists of a k-v-pair
isn't that what std::map does internally?

**Comment by degski** [comment]
> 
> 
> > or better, create an intrusive map with std::set, i.e. the 'key' consists of a k-v-pair
>> isn't that what std::map does internally?

The answer is probably yes, but you'll be depending on implementation.
