### ISSUE TITLE
Add check for _MSVC_LANG in addition to __cplusplus

### ISSUE THREAD

**Issue by EvanBalster** [Tessil/hat-trie#34]
Hello —

It's all a bit daft, but the Microsoft Visual Studio compilers report `__cplusplus` as `199711L` by default, even when using modern C++ standards.  This behavior can be remedied using the `/Zc:__cplusplus` switch, *or* by detecting the `_MSVC_LANG` macro (whose value will be greater than or equal to `__cplusplus` and more representative of the standard used).

https://docs.microsoft.com/en-us/cpp/build/reference/zc-cplusplus?view=msvc-160

This would allow for use of string_view in a "blank" MSVC project.

https://github.com/Tessil/hat-trie/blob/master/include/tsl/htrie_hash.h

**Comment by Tessil** [comment]
Hi,

Thank you for reporting the issue and providing a fix. I merged #35 I will thus close this issue.
