### ISSUE TITLE
cmake --build . <- failed with boost 1.70

### ISSUE THREAD

**Issue by superdolt** [Tessil/hat-trie#42]
cmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/local/include (found suitable version "1.70.0", minimum required is "1.54.0") found components: unit_test_framework 
-- Configuring done
-- Generating done
-- Build files have been written to: 

Scanning dependenccmake ..
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Boost: /usr/local/include (found suitable version "1.70.0", minimum required is "1.54.0") found components: unit_test_framework 
-- Configuring done
-- Generating done
ies of target tsl_hat_trie_tests
[ 25%] Building CXX object CMakeFiles/tsl_hat_trie_tests.dir/main.cpp.o
[ 50%] Building CXX object CMakeFiles/tsl_hat_trie_tests.dir/trie_map_tests.cpp.o
/trie_map_tests.cpp: In member function 'void test_htrie_map::test_empty_map::test_method()':
/trie_map_tests.cpp:739:22: error: '*((void*)& last +65)' may be used uninitialized in this function [-Werror=maybe-uninitialized]
  739 | BOOST_AUTO_TEST_CASE(test_empty_map) {
      |                      ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[2]: *** [CMakeFiles/tsl_hat_trie_tests.dir/build.make:76: CMakeFiles/tsl_hat_trie_tests.dir/trie_map_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:96: CMakeFiles/tsl_hat_trie_tests.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

**Comment by Tessil** [comment]
The CI uses Boost 1.78 and I have 1.74 locally and everything is working fine. Could you try to eventually update Boost?

**Comment by Tessil** [comment]
Closing as out-of-date.
