### ISSUE TITLE
possible to pls show how to use emplace function?

### ISSUE THREAD

**Issue by superdolt** [Tessil/hat-trie#46]
by the way, what's emplace? is there a replace function and how to use? thx

**Comment by Tessil** [comment]
The `emplace` method is similar to the [`std::unordered_map::emplace`](https://en.cppreference.com/w/cpp/container/unordered_map/emplace) function and construct the new element in-place.

To replace an element use the `operator[]` like [`std::unordered_map::operator[]`](https://en.cppreference.com/w/cpp/container/unordered_map/operator_at).
