### ISSUE TITLE
Is load factor 16 or greater possible?

### ISSUE THREAD

**Issue by hiqsociety** [Tessil/hat-trie#48]
1. is load factor 16 or greater possible?
2. What's the maximum load factor possible? what does load factor mean? 
3. Possible to have mem usage lower than the actual size of the data?

**Comment by Tessil** [comment]
1. Yes
2. No hard-coded limit but raising it higher than 4 is probably not a good idea. The load factor is `size()/`bucket_count().
3. Yes if there're a lot of common prefix in your data.
