### ISSUE TITLE
windows conflict with windows.h

### ISSUE THREAD

**Issue by yangxingpping** [Tessil/hat-trie#49]
#include <iostream>
#include <windows.h>
#include <algorithm>
#include "tsl/htrie_map.h"
int main()
{
    std::cout << "Hello World!\n";
}

tsl\array-hash\array_growth_policy.h(96,48): warning C4003: not enough arguments for function-like macro invocation 'max'
tsl\array-hash\array_growth_policy.h(96,48): error C2589: '(': illegal token on right side of '::'
tsl\array-hash\array_growth_policy.h(133): message : see reference to class template instantiation 'tsl::ah::power_of_two_growth_policy<GrowthFactor>' being compiled
tsl\array-hash\array_growth_policy.h(185,61): warning C4003: not enough arguments for function-like macro invocation 'max'
tsl\array-hash\array_growth_policy.h(185,61): error C2589: '(': illegal token on right side of '::'
tsl\array-hash\array_growth_policy.h(192): message : see reference to class template instantiation 'tsl::ah::mod_growth_policy<GrowthFactor>' being compiled
tsl\array-hash\array_growth_policy.h(185,61): error C2059: syntax error: '('

[https://stackoverflow.com/questions/2789481/problem-calling-stdmax](url)

maybe add macro NOMINMAX in CMakeLists.txt

**Comment by Tessil** [comment]
Sorry I prefer to not add such overarching macro to the CMakeLists, I'll leave it to the users.
