### ISSUE TITLE
Wiki dataset from benchmarks cannot be download (404 error)

### ISSUE THREAD

**Issue by Bazist** [Tessil/hat-trie#5]
Hi,
I am author HArray
https://github.com/Bazist/HArray
KV storage that also kind of Trie structure. 
High performance and variety functionality in 8k code lines.
I want to test under your dataset my structure, but here is 404 error
https://dumps.wikimedia.org/enwiki/20170320/

Could you help me, where a I can download the dataset ?
Thanks.

**Comment by Tessil** [comment]
Hi,

Effectively the link seems dead, Wikimedia doesn't seem to keep the old data for too long. I will see if I can upload the file I have.

But you can use a more recent dump, see https://dumps.wikimedia.org/enwiki/.

**Comment by Bazist** [comment]
Thanks, I have download one.
