### ISSUE TITLE
trie node has no value node and no child

### ISSUE THREAD

**Issue by KKKIIO** [Tessil/hat-trie#6]
According to the comment in code:
> A trie node should at least have one child, except if it has a value node then no child is a possibility.

I add following assert to `iterator htrie_hash::erase(iterator pos)`:
```cpp
if(pos.m_read_trie_node_value) {
    tsl_assert(pos.m_current_trie_node != nullptr && pos.m_current_trie_node->val_node() != nullptr);
    tsl_assert(pos.m_current_trie_node->nb_children() > 0); // here
    pos.m_current_trie_node->val_node().reset(nullptr);
    m_nb_elements--;        
    return next_pos;
}
```
And write a test case:
```cpp
BOOST_AUTO_TEST_CASE(stest_empty_trie_node) {
	tsl::htrie_set<char> set = { "k1", "k2", "k3", "k4" };
	set.burst_threshold(4);
	set.insert("k");
	set.erase("k1");
	set.erase("k2");
	set.erase("k3");
	set.erase("k4");
	set.erase("k");
}
```
It cause the assert fail. Is it a bug?

By the way,  code coverage testing will make unit tests more complete.
Thanks for your implement.

**Comment by Tessil** [comment]
Thank you very much for the report.

It seems to be effectively a bug. It should not affect the find and insert methods but may cause problems when incrementing an iterator. 

I'll not be able to really investigate that this week but I'll provide a correction next week.

**Comment by KKKIIO** [comment]
The reason I do the test is that I saw there is no check whether `node` has children when remove the val node of `node`:
```cpp
if(pos.m_read_trie_node_value) {
	tsl_assert(pos.m_current_trie_node != nullptr && pos.m_current_trie_node->val_node() != nullptr);
	
	pos.m_current_trie_node->val_node().reset(nullptr);
	m_nb_elements--;
	
	return next_pos;
}
```
And I found that in `clear_empty_nodes`, when parent has val node, the hash_node child will be simply removed, which may make its parent have no child:
```cpp
else if(parent->val_node() != nullptr || parent->nb_children() > 1) {
    parent->child(empty_hnode.child_of_char()).reset(nullptr);
}
```

Hope this infomation can help you.

**Comment by Tessil** [comment]
Sorry for the delay, I was a bit busy.

I made the correction, it effectively can cause problems on iterations (but not find, erase, ... outside of taking a bit more memory).

Regarding the second point in `clear_empty_nodes` it's alright if the child is removed. A `trie_node` must either have at least one child and/**or** a `value_node` (which the `else if` makes sure of).
